spring.application.name=task-list

spring.datasource.url=jdbc:postgresql://localhost:5432/todo-list
spring.datasource.username=postgres
spring.datasource.password=W1nWKJnn
server.port=8081

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=guiguilsantana@gmail.com
spring.mail.password=tiov dtth khnj lwlb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true